"use client"

import Link from "next/link"
import { useParams, usePathname, useRouter } from "next/navigation"
import { BarChart3Icon, BellIcon, BookOpenCheckIcon, BriefcaseBusinessIcon, ClipboardCheckIcon, CreditCardIcon, FileArchiveIcon, FileCheck2Icon, FileTextIcon, FlagIcon, FolderKanbanIcon, FolderOpenIcon, GraduationCapIcon, LayoutDashboardIcon, LightbulbIcon, LogOutIcon, MessageSquareTextIcon, NotebookPenIcon, PresentationIcon, SettingsIcon, ShieldCheckIcon, TargetIcon, UserRoundIcon, UsersIcon } from "lucide-react"
import type { CurrentUser } from "@/lib/auth"
import { createClient } from "@/lib/supabase/client"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"

const nav = {
  student: [["dashboard","Overview",LayoutDashboardIcon],["onboarding","Profile & onboarding",UserRoundIcon],["project-ideas","Project ideas",LightbulbIcon],["projects","My projects",FolderKanbanIcon],["planner","Weekly planner",ClipboardCheckIcon],["evidence","Evidence vault",FileArchiveIcon],["reflections","Reflection journal",NotebookPenIcon],["skills","Skills tracker",TargetIcon],["feedback","Counselor feedback",MessageSquareTextIcon],["portfolio","Portfolio builder",BriefcaseBusinessIcon],["presentation","Presentation builder",PresentationIcon],["recommendation-evidence","Recommendation evidence",FileCheck2Icon],["subscription","Subscription",CreditCardIcon]],
  counselor: [["dashboard","Overview",LayoutDashboardIcon],["students","Assigned students",UsersIcon],["proposals","Project proposals",FolderOpenIcon],["weekly-progress","Weekly progress",ClipboardCheckIcon],["evidence","Evidence review",FileArchiveIcon],["reflections","Reflection review",NotebookPenIcon],["skills","Skills confirmation",TargetIcon],["progress-reports","Progress reports",FileTextIcon],["subscription","Subscription",CreditCardIcon]],
  administrator: [["dashboard","Overview",BarChart3Icon],["users","Users",UsersIcon],["assignments","Assignments",GraduationCapIcon],["categories","Categories",FolderOpenIcon],["templates","Project templates",BookOpenCheckIcon],["plans","Plans",CreditCardIcon],["flags","Flagged content",FlagIcon],["settings","Platform settings",SettingsIcon]],
} as const

export function AppShell({ user, children }: { user: CurrentUser; children: React.ReactNode }) {
  const params = useParams<{ locale: string }>(); const locale = params.locale ?? "en"; const pathname = usePathname(); const router = useRouter()
  const rolePath = user.role === "administrator" ? "admin" : user.role
  async function logout(){ await createClient().auth.signOut(); router.push(`/${locale}/login`); router.refresh() }
  return <SidebarProvider><Sidebar collapsible="icon"><SidebarHeader className="h-16 justify-center border-b px-4"><Link href={`/${locale}/${rolePath}/dashboard`} className="font-heading text-lg font-semibold tracking-tight text-sidebar-foreground">Portfolio<span className="text-accent">Path</span></Link></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>{user.role === "administrator" ? "Administration" : user.role === "counselor" ? "Counselor workspace" : "Student workspace"}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav[user.role].map(([slug,label,Icon]) => { const href = `/${locale}/${rolePath}/${slug}`; return <SidebarMenuItem key={slug}><SidebarMenuButton asChild isActive={pathname === href} tooltip={label}><Link href={href}><Icon/><span>{label}</span></Link></SidebarMenuButton></SidebarMenuItem> })}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild><Link href={`/${locale}/ethical-use`}><ShieldCheckIcon/><span>Ethical use</span></Link></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter></Sidebar><SidebarInset><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-card/95 px-4 backdrop-blur md:px-7"><div className="flex items-center gap-3"><SidebarTrigger/><span className="hidden text-sm text-muted-foreground sm:inline">Authentic work. Documented clearly.</span></div><div className="flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Notifications"><BellIcon/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="h-10 gap-2 px-2"><Avatar className="size-8"><AvatarFallback>{user.full_name.split(" ").map(value=>value[0]).slice(0,2).join("") || "PP"}</AvatarFallback></Avatar><span className="hidden max-w-40 truncate text-sm sm:block">{user.full_name}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{user.role}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={logout}><LogOutIcon/>Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main id="main" className="min-h-[calc(100vh-4rem)] p-4 md:p-7 lg:p-9">{children}</main></SidebarInset></SidebarProvider>
}
