import Link from "next/link"
import { CheckIcon, ShieldCheckIcon } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { MarketingHeader } from "@/components/marketing-header"
import { SiteFooter } from "@/components/site-footer"

const content: Record<string,{title:string;intro:string;sections:{title:string;body:string;items?:string[]}[]}> = {
  "how-it-works": { title:"A clear path from interest to documented work.", intro:"PortfolioPath helps students plan, complete, evidence, reflect on, and present one authentic project at a time.", sections:[{title:"1. Start with reality",body:"Profile, time, budget, access, and existing interests define what is feasible."},{title:"2. Build week by week",body:"Milestones, tasks, evidence, and reflections keep the work student-owned."},{title:"3. Review facts",body:"Counselors verify evidence and skills without writing the student's story."}] },
  students: { title:"Your interests can become credible projects.", intro:"Use structure and evidence to show how you think, decide, adapt, and finish.", sections:[{title:"Plan",body:"Generate realistic suggestions and turn one into a ten-step blueprint.",items:["Autosaving onboarding","Three suggestion cards","Measurable outcomes"]},{title:"Document",body:"Keep weekly tasks, evidence, and concrete reflections together.",items:["Private evidence vault","Weekly and final reflections","Three-state skills tracker"]},{title:"Present",body:"Build an editable portfolio, presentation, and recommender evidence summary.",items:["Private share links","PDF export","Factual guidance labels"]}] },
  counselors: { title:"Review more clearly, with evidence close at hand.", intro:"A compact review workspace for independent counselors and small application offices.", sections:[{title:"One review queue",body:"Filter proposals, tasks, evidence, and reflections by student and urgency."},{title:"Factual confirmation",body:"Open linked evidence before confirming a skill or outcome."},{title:"Professional summaries",body:"Generate progress summaries from verified records only."}] },
  pricing: { title:"Simple plans for a focused outcome.", intro:"Transparent Turkish-lira pricing with no admissions or scholarship guarantees.", sections:[{title:"Free Assessment · ₺0",body:"Onboarding, readiness assessment, and one limited direction."},{title:"Project Blueprint · ₺1,200",body:"Three ideas, one complete blueprint, and a downloadable plan."},{title:"Complete Portfolio · ₺5,500",body:"Up to three projects, evidence, review, portfolio, presentation, and PDF."},{title:"Counselor Professional · ₺2,500/month",body:"Up to 25 assigned students, reviews, templates, and progress summaries."}] },
  "ethical-use": { title:"Authenticity is a product requirement.", intro:"PortfolioPath guides students without manufacturing credentials, observations, or impact.", sections:[{title:"The system never invents",body:"Achievements, participants, partnerships, mentor comments, certificates, impact data, admission outcomes, or scholarship outcomes."},{title:"Plans remain plans",body:"Future work and intended outcomes stay clearly labeled until evidence supports completion."},{title:"Students confirm accuracy",body:"Portfolio sharing, PDF export, and evidence summaries require a factual-accuracy confirmation."}] },
  privacy: { title:"Privacy policy", intro:"PortfolioPath uses private-by-default student records and evidence storage.", sections:[{title:"Data collected",body:"Account, onboarding, project, evidence, reflection, review, billing, and audit data required to provide the service."},{title:"Access",body:"Students access their records; approved assigned counselors access review records; audited administrators handle platform operations."},{title:"Control",body:"Users may request export or deletion. Private links expire and can be revoked immediately."}] },
  terms: { title:"Terms of use", intro:"Use PortfolioPath only for genuine, lawful, student-owned work.", sections:[{title:"Acceptable use",body:"Do not upload unlawful content, private third-party data without permission, fabricated records, or work presented under a false identity."},{title:"No admissions guarantee",body:"PortfolioPath provides workflow and documentation tools, not admission, scholarship, or legal advice."},{title:"Account safety",body:"Users are responsible for accurate account information and protecting credentials."}] },
}

export function PublicContentPage({ locale, slug }: { locale:string; slug:string }) { const page=content[slug]; return <><MarketingHeader locale={locale}/><main id="main"><section className="border-b bg-card"><div className="mx-auto max-w-5xl px-5 py-18 lg:px-8"><h1 className="max-w-4xl text-4xl font-semibold text-primary md:text-5xl">{page.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{page.intro}</p></div></section><section><div className="mx-auto grid max-w-5xl gap-5 px-5 py-14 md:grid-cols-2 lg:px-8">{page.sections.map(section=><Card key={section.title}><CardHeader><CardTitle>{section.title}</CardTitle><CardDescription>{section.body}</CardDescription></CardHeader>{section.items&&<CardContent><ul className="flex flex-col gap-3">{section.items.map(item=><li key={item} className="flex items-center gap-2 text-sm"><CheckIcon className="size-4 text-success"/>{item}</li>)}</ul></CardContent>}</Card>)}</div></section>{slug==="ethical-use"&&<section className="mx-auto max-w-5xl px-5 pb-14 lg:px-8"><Alert><ShieldCheckIcon/><AlertTitle>Evidence for recommenders—not recommendation letters</AlertTitle><AlertDescription>Recommendation evidence summaries must never contain invented observations.</AlertDescription></Alert></section>}<section className="border-t bg-card"><div className="mx-auto flex max-w-5xl flex-col items-start gap-5 px-5 py-12 md:flex-row md:items-center md:justify-between lg:px-8"><div><h2 className="text-2xl font-semibold">Ready to document real work?</h2><p className="mt-1 text-muted-foreground">Begin with the free assessment.</p></div><Button asChild><Link href={`/${locale}/register`}>Get started</Link></Button></div></section></main><SiteFooter locale={locale}/></> }
