import Link from "next/link"
import { CheckIcon, ShieldCheckIcon } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { MarketingHeader } from "@/components/marketing-header"
import { SchoolQuoteForm } from "@/components/school-quote-form"
import { SiteFooter } from "@/components/site-footer"

type ContentPage = { title: string; intro: string; sections: Array<{ title: string; body: string; items?: string[] }> }

const english: Record<string, ContentPage> = {
  "how-it-works": { title: "A clear path from interest to documented work.", intro: "PortfolioPath helps students plan, complete, document, reflect on, and present one authentic project at a time.", sections: [{ title: "1. Start with reality", body: "Profile, time, budget, access, and existing interests define what is feasible." }, { title: "2. Build week by week", body: "Milestones, tasks, evidence, and reflections keep the work student-owned." }, { title: "3. Review facts", body: "Counselors verify evidence and skills without writing the student's story." }] },
  students: { title: "Your interests can become credible projects.", intro: "Use structure and evidence to show how you think, decide, adapt, and finish.", sections: [{ title: "Plan", body: "Generate realistic suggestions and turn one into a ten-step blueprint.", items: ["Autosaving onboarding", "Three tailored suggestions", "Measurable planned outcomes"] }, { title: "Document", body: "Keep weekly tasks, evidence, and concrete reflections together.", items: ["Private evidence vault", "Weekly and final reflections", "Three-state skills tracker"] }, { title: "Present", body: "Build an editable portfolio, presentation, and recommender evidence summary.", items: ["Private revocable share links", "PDF export", "Factual guidance labels"] }] },
  counselors: { title: "Review more clearly, with evidence close at hand.", intro: "A focused workspace for independent counselors and small application offices.", sections: [{ title: "One review queue", body: "Review proposals, tasks, evidence, and reflections by student and urgency." }, { title: "Factual confirmation", body: "Open linked accepted evidence before confirming a skill or outcome." }, { title: "Professional summaries", body: "Generate progress summaries from verified records only." }] },
  parents: { title: "Stay informed without taking over the student’s work.", intro: "Parents join through a student-created invitation and see only consented milestones, selected evidence, and shared counselor updates.", sections: [{ title: "Consent first", body: "The student controls the connection and can revoke it. Private reflections are not visible by default." }, { title: "Calm progress view", body: "See project milestones, deadlines, and selected evidence without an admissions score or a public profile." }, { title: "Included with the portfolio", body: "Parent access is included with Complete Student Portfolio. It is not a separate family subscription." }] },
  schools: { title: "A private, evidence-first workspace for schools.", intro: "School Partnership is an annual, quote-led plan for cohorts, counselor workflows, ethical templates, and privacy-safe completion insights.", sections: [{ title: "Organization boundaries", body: "School staff see only their own organization, memberships, cohorts, and enrolled students." }, { title: "Student ownership", body: "Schools can provide structure without turning authentic projects into mass-produced applications." }, { title: "Annual partnership", body: "Seats, onboarding, templates, counselor access, and reporting are scoped after a qualified conversation." }] },
  pricing: { title: "Simple plans for a focused outcome.", intro: "Transparent Turkish-lira pricing with no admissions or scholarship guarantees.", sections: [{ title: "Free Assessment · ₺0", body: "Profile, readiness assessment, one limited direction, and an ethical upgrade path." }, { title: "Project Blueprint · ₺1,200", body: "Three ideas, one complete blueprint, weekly plan, and evidence checklist." }, { title: "Complete Student Portfolio · ₺5,500", body: "Up to three projects, evidence, reflections, mentor verification, parent access, application preparation, portfolio, presentation, and PDF export." }, { title: "Counselor Professional · ₺2,500/month", body: "Up to 25 assigned students, reviews, templates, skill confirmation, and factual progress summaries." }, { title: "School Partnership · annual quote", body: "Organization seats, cohorts, counselor tools, onboarding, templates, and private completion insights." }] },
  "ethical-use": { title: "Authenticity is a product requirement.", intro: "PortfolioPath guides students without manufacturing credentials, observations, or impact.", sections: [{ title: "The system never invents", body: "Achievements, participants, partnerships, mentor comments, certificates, impact data, admission outcomes, or scholarship outcomes." }, { title: "Plans remain plans", body: "Future work and intended outcomes stay clearly labeled until evidence supports completion." }, { title: "Students confirm accuracy", body: "Portfolio sharing, PDF export, and evidence summaries require a factual-accuracy confirmation." }] },
  privacy: { title: "Privacy policy", intro: "PortfolioPath uses private-by-default student records and evidence storage.", sections: [{ title: "Data collected", body: "Account, onboarding, project, evidence, reflection, review, billing, and audit data required to provide the service." }, { title: "Access", body: "Students access their records; assigned counselors access review records; parents and mentors receive strictly limited scopes." }, { title: "Control", body: "Users may request export or deletion. Private links expire and can be revoked immediately." }] },
  terms: { title: "Terms of use", intro: "Use PortfolioPath only for genuine, lawful, student-owned work.", sections: [{ title: "Acceptable use", body: "Do not upload unlawful content, private third-party data without permission, fabricated records, or work presented under a false identity." }, { title: "No admissions guarantee", body: "PortfolioPath provides workflow and documentation tools, not admission, scholarship, or legal advice." }, { title: "Account safety", body: "Users are responsible for accurate account information and protecting credentials." }] },
}

const turkish: Record<string, ContentPage> = {
  "how-it-works": { title: "İlgi alanından belgelenmiş çalışmaya net bir yol.", intro: "PortfolioPath, öğrencilerin gerçek bir projeyi planlamasına, tamamlamasına, belgelemesine, üzerine düşünmesine ve sunmasına yardımcı olur.", sections: [{ title: "1. Gerçek durumla başlayın", body: "Profil, zaman, bütçe, erişim ve mevcut ilgi alanları uygulanabilir olanı belirler." }, { title: "2. Her hafta ilerleyin", body: "Kilometre taşları, görevler, kanıtlar ve yansımalar çalışmayı öğrencinin sahipliğinde tutar." }, { title: "3. Gerçekleri inceleyin", body: "Danışmanlar öğrencinin hikâyesini yazmadan kanıtları ve becerileri doğrular." }] },
  students: { title: "İlgi alanlarınız güvenilir projelere dönüşebilir.", intro: "Nasıl düşündüğünüzü, karar verdiğinizi, uyum sağladığınızı ve tamamladığınızı kanıtlarla gösterin.", sections: [{ title: "Planla", body: "Gerçekçi öneriler üretin ve birini on adımlı proje planına dönüştürün.", items: ["Otomatik kaydeden onboarding", "Üç kişiselleştirilmiş öneri", "Ölçülebilir planlanan çıktılar"] }, { title: "Belgele", body: "Haftalık görevleri, kanıtları ve somut yansımaları bir arada tutun.", items: ["Özel kanıt kasası", "Haftalık ve final yansımaları", "Üç durumlu beceri takibi"] }, { title: "Sun", body: "Düzenlenebilir portföy, sunum ve referans kanıt özeti hazırlayın.", items: ["İptal edilebilir özel paylaşım bağlantıları", "PDF dışa aktarma", "Gerçeklik uyarıları"] }] },
  counselors: { title: "Kanıtlar yanınızdayken daha net inceleyin.", intro: "Bağımsız danışmanlar ve küçük başvuru ofisleri için odaklı çalışma alanı.", sections: [{ title: "Tek inceleme kuyruğu", body: "Önerileri, görevleri, kanıtları ve yansımaları öğrenciye ve önceliğe göre inceleyin." }, { title: "Gerçeklere dayalı doğrulama", body: "Bir beceri veya sonucu doğrulamadan önce bağlantılı kabul edilmiş kanıtı açın." }, { title: "Profesyonel özetler", body: "Yalnızca doğrulanmış kayıtlardan ilerleme özeti üretin." }] },
  parents: { title: "Öğrencinin çalışmasını devralmadan bilgi sahibi olun.", intro: "Veliler, öğrenci tarafından oluşturulan davetle katılır ve yalnızca onaylanmış kilometre taşlarını, seçilmiş kanıtları ve danışman güncellemelerini görür.", sections: [{ title: "Önce onay", body: "Bağlantıyı öğrenci kontrol eder ve iptal edebilir. Özel yansımalar varsayılan olarak görünmez." }, { title: "Sakin ilerleme görünümü", body: "Kabul puanı veya halka açık profil olmadan kilometre taşlarını, tarihleri ve seçilmiş kanıtları görün." }, { title: "Pakete dahildir", body: "Veli erişimi Complete Student Portfolio paketine dahildir; ayrı bir aile aboneliği değildir." }] },
  schools: { title: "Okullar için özel ve kanıt-odaklı çalışma alanı.", intro: "School Partnership; kohortlar, danışman iş akışları, etik şablonlar ve gizlilik güvenli tamamlanma içgörüleri için yıllık teklifli plandır.", sections: [{ title: "Kurum sınırları", body: "Okul personeli yalnızca kendi kurumunu, üyeliklerini, kohortlarını ve kayıtlı öğrencilerini görür." }, { title: "Öğrenci sahipliği", body: "Okullar, gerçek projeleri seri üretilmiş başvurulara dönüştürmeden yapı sunabilir." }, { title: "Yıllık iş ortaklığı", body: "Kontenjanlar, onboarding, şablonlar, danışman erişimi ve raporlama nitelikli görüşmeden sonra belirlenir." }] },
  pricing: english.pricing,
  "ethical-use": english["ethical-use"],
  privacy: english.privacy,
  terms: english.terms,
}

export function PublicContentPage({ locale, slug }: { locale: string; slug: string }) {
  const language = locale === "tr" ? turkish : english
  const page = language[slug] ?? english[slug]
  return <><MarketingHeader locale={locale} /><main id="main"><section className="border-b bg-card"><div className="mx-auto max-w-5xl px-5 py-18 lg:px-8"><h1 className="max-w-4xl text-4xl font-semibold text-primary md:text-5xl">{page.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{page.intro}</p></div></section><section><div className="mx-auto grid max-w-5xl gap-5 px-5 py-14 md:grid-cols-2 lg:px-8">{page.sections.map((section) => <Card key={section.title}><CardHeader><CardTitle>{section.title}</CardTitle><CardDescription>{section.body}</CardDescription></CardHeader>{section.items ? <CardContent><ul className="flex flex-col gap-3">{section.items.map((item) => <li className="flex items-center gap-2 text-sm" key={item}><CheckIcon className="size-4 text-success" />{item}</li>)}</ul></CardContent> : null}</Card>)}</div></section>{slug === "schools" ? <section className="mx-auto max-w-5xl px-5 pb-14 lg:px-8"><SchoolQuoteForm /></section> : null}{slug === "ethical-use" ? <section className="mx-auto max-w-5xl px-5 pb-14 lg:px-8"><Alert><ShieldCheckIcon /><AlertTitle>Evidence for recommenders—not recommendation letters</AlertTitle><AlertDescription>Recommendation evidence summaries must never contain invented observations.</AlertDescription></Alert></section> : null}<section className="border-t bg-card"><div className="mx-auto flex max-w-5xl flex-col items-start gap-5 px-5 py-12 md:flex-row md:items-center md:justify-between lg:px-8"><div><h2 className="text-2xl font-semibold">{locale === "tr" ? "Gerçek çalışmayı belgelemeye hazır mısınız?" : "Ready to document real work?"}</h2><p className="mt-1 text-muted-foreground">{locale === "tr" ? "Ücretsiz değerlendirmeyle başlayın." : "Begin with the free assessment."}</p></div><Button asChild><Link href={`/${locale}/register`}>{locale === "tr" ? "Başlayın" : "Get started"}</Link></Button></div></section></main><SiteFooter locale={locale} /></>
}
