import type { GeneratedResult, GenerationContext, GenerationProvider, PresentationDraft, ProjectIdea, ProgressSummary, RecommendationEvidence } from "./types"

function wrap<T>(data: T, context: GenerationContext, warnings: string[] = []): GeneratedResult<T> { return { data, provenance: { sourceRecordIds: context.sourceRecordIds, guidanceLabel: "Editable guidance generated from verified PortfolioPath records.", warnings, requiresFactualConfirmation: true } } }

export class TemplateGenerationProvider implements GenerationProvider {
  async projectIdeas(input: Record<string, unknown>, context: GenerationContext) {
    const major = String(input.intendedMajor || "your intended field")
    const hours = Math.max(1, Math.min(8, Number(input.weeklyHours) || 3))
    const base: ProjectIdea[] = [
      { title: "Document a local observation study", category: "Research", description: "Choose one observable local question, keep a dated field log, and publish a concise findings brief.", fit: `Connects genuine interests with ${major} through a feasible evidence trail.`, majorConnection: `Uses research habits relevant to ${major}.`, durationWeeks: 6, weeklyHours: hours, estimatedCostTry: 250, finalDeliverable: "Illustrated findings brief", expectedEvidence: ["dated field notes","method draft","source list","final brief"], targetSkills: ["Research","Writing","Data analysis"], measurableOutcomes: ["Complete four observation sessions","Cite at least five reliable sources","Produce one reviewed final brief"], risks: ["Insufficient observations","Scope becomes too broad"], ethicalNotes: ["Separate observation from conclusion","Do not invent participants or impact"], suggestionOnly: true },
      { title: "Build a useful bilingual digital guide", category: "Coding and technology", description: "Create and test a small website that explains a local topic to an international audience.", fit: `Combines student ownership with a practical ${major} connection.`, majorConnection: `Shows planning, iteration, communication, and digital literacy relevant to ${major}.`, durationWeeks: 8, weeklyHours: hours, estimatedCostTry: 500, finalDeliverable: "Deployed bilingual website", expectedEvidence: ["repository commits","wireframes","test notes","deployment link"], targetSkills: ["Coding","Organization","Communication"], measurableOutcomes: ["Build four accessible pages","Document three user tests","Publish a change log"], risks: ["Technical scope expands","User testers unavailable"], ethicalNotes: ["Do not claim partnerships without confirmation","Use licensed media"], suggestionOnly: true },
      { title: "Create an evidence-backed community resource", category: "Social impact", description: "Identify a narrow information need, interview or consult appropriate sources, and produce a verified resource.", fit: `Turns a real concern into a manageable project related to ${major}.`, majorConnection: `Demonstrates applied communication and responsible problem-solving for ${major}.`, durationWeeks: 7, weeklyHours: hours, estimatedCostTry: 300, finalDeliverable: "Bilingual resource pack", expectedEvidence: ["research notes","consent records","draft revisions","distribution log"], targetSkills: ["Initiative","Communication","Resilience"], measurableOutcomes: ["Consult three consented sources","Complete two revision rounds","Publish one factual resource"], risks: ["Access to sources","Privacy concerns"], ethicalNotes: ["Get consent for quotations","Report reach without exaggeration"], suggestionOnly: true },
    ]
    return wrap(base, context, ["These are suggestions, not completed achievements."])
  }
  async presentation(input: Record<string, unknown>, context: GenerationContext) { const title=String(input.title||"My project"), objective=String(input.objective||"complete a documented objective"); const data:PresentationDraft={pitch30:`I created ${title} to ${objective}. I documented my decisions, evidence, and what changed along the way.`,explanation90:`${title} began with a genuine question. My objective was to ${objective}. I planned weekly work, kept evidence, reflected on challenges, and revised the project when the evidence required it.`,presentation3m:`Introduce the motivation for ${title}, explain the objective, describe verified actions in sequence, show selected evidence, discuss one challenge and adaptation, then close with what you learned and what you would do next.`,interviewQuestions:["Why did you choose this project?","What changed from your original plan?","Which evidence best represents your contribution?","What was your most difficult decision?","What would you develop next?"],answerNotes:["Use one concrete example per answer.","Distinguish plans from completed work.","Name uncertainty rather than exaggerating impact."]}; return wrap(data,context) }
  async recommendationEvidence(input: Record<string, unknown>, context: GenerationContext) { const data:RecommendationEvidence={warning:"This document provides evidence for a recommender. It is not a recommendation letter and must not contain invented observations.",context:String(input.context||"Project context is drawn from verified PortfolioPath records."),completedActions:Array.isArray(input.completedActions)?input.completedActions as string[]:[],initiativeEvidence:Array.isArray(input.initiativeEvidence)?input.initiativeEvidence as string[]:[],reliabilityEvidence:Array.isArray(input.reliabilityEvidence)?input.reliabilityEvidence as string[]:[],problemSolvingEvidence:Array.isArray(input.problemSolvingEvidence)?input.problemSolvingEvidence as string[]:[],resilienceEvidence:Array.isArray(input.resilienceEvidence)?input.resilienceEvidence as string[]:[],communicationEvidence:Array.isArray(input.communicationEvidence)?input.communicationEvidence as string[]:[],confirmedSkills:Array.isArray(input.confirmedSkills)?input.confirmedSkills as string[]:[],outcomes:Array.isArray(input.outcomes)?input.outcomes as string[]:[]}; return wrap(data,context,["Only reviewed evidence and counselor-confirmed skills are included."]) }
  async progressSummary(input: Record<string, unknown>, context: GenerationContext) { const data:ProgressSummary={period:String(input.period||"Current project period"),completed:(input.completed as string[])||[],evidenceReviewed:(input.evidenceReviewed as string[])||[],reflections:(input.reflections as string[])||[],counselorConfirmedSkills:(input.confirmedSkills as string[])||[],concerns:(input.concerns as string[])||[],nextSteps:(input.nextSteps as string[])||[]}; return wrap(data,context) }
}
