import { notFound } from "next/navigation"
import { Clock3Icon, LockKeyholeIcon, ShieldCheckIcon } from "lucide-react"
import { Brand } from "@/components/brand"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { createAdminClient } from "@/lib/supabase/admin"
import { hashShareToken } from "@/lib/security"
export const dynamic="force-dynamic"
export default async function SharedPortfolio({params}:{params:Promise<{token:string}>}){const {token}=await params;if(!process.env.SUPABASE_SECRET_KEY&&!process.env.SUPABASE_SERVICE_ROLE_KEY)notFound();const admin=createAdminClient();const {data:link}=await admin.from("share_links").select("id,expires_at,revoked_at,portfolio_page_id").eq("token_hash",hashShareToken(token)).maybeSingle();if(!link||link.revoked_at||new Date(link.expires_at)<=new Date())notFound();const {data:page}=await admin.from("portfolio_pages").select("title,confirmed_at,portfolio_sections(title,content,visible,sort_order),projects(title,start_date,end_date,main_objective,student_id)").eq("id",link.portfolio_page_id).single();if(!page?.confirmed_at)notFound();await admin.from("share_links").update({last_accessed_at:new Date().toISOString()}).eq("id",link.id);const sections=(page.portfolio_sections??[]).filter((section:{visible:boolean})=>section.visible).sort((a:{sort_order:number},b:{sort_order:number})=>a.sort_order-b.sort_order);return <main id="main" className="min-h-screen bg-background"><header className="border-b bg-card"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><Brand/><Badge variant="outline"><LockKeyholeIcon/>Private share</Badge></div></header><article className="mx-auto max-w-4xl px-5 py-12"><div className="border-b pb-8"><p className="text-xs font-semibold tracking-[.16em] text-secondary uppercase">Documented student project</p><h1 className="mt-3 text-4xl font-semibold text-primary md:text-5xl">{page.title}</h1><p className="mt-4 text-sm text-muted-foreground">This page separates student-authored statements, planned targets, and evidence-supported records.</p></div><Alert className="my-8"><ShieldCheckIcon/><AlertTitle>Factual accuracy confirmed</AlertTitle><AlertDescription>This private page was confirmed before sharing. Counselor confirmation, where present, is labeled separately.</AlertDescription></Alert><div className="space-y-10">{sections.map((section:{title:string;content:unknown;sort_order:number})=><section key={section.title}><h2 className="text-2xl font-semibold text-primary">{section.title}</h2><div className="mt-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{typeof section.content==="string"?section.content:JSON.stringify(section.content,null,2)}</div></section>)}</div><footer className="mt-12 flex items-center gap-2 border-t pt-6 text-xs text-muted-foreground"><Clock3Icon className="size-4"/>Link expires {new Date(link.expires_at).toLocaleDateString()}</footer></article></main>}
